site_name: Mindustry Mod Wiki
site_url: https://nullotte.github.io/MindustryModWiki/
repo_url: https://github.com/nullotte/MindustryModWiki/
theme:
  name: material
  features:
    - navigation.indexes
    - navigation.prune
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
extra_css:
  - stylesheets/extra.css

nav:
  - index.md