site_name: Mindustry Mod Wiki
site_url: https://nullotte.github.io/MindustryModWiki/
repo_url: https://github.com/nullotte/MindustryModWiki/
theme:
  name: material
  features:
    - navigation.indexes
    - navigation.prune
extra_css:
  - stylesheets/extra.css

nav:
  - index.md